-- Faithful port of Neovim runtime's quiet.vim colorscheme.
-- Source: https://github.com/neovim/neovim/blob/master/runtime/colors/quiet.vim
-- Original author: Maxence Weynans <neutaaaaan@gmail.com>

vim.cmd("source $VIMRUNTIME/colors/vim.lua")
vim.g.colors_name = "quiet-nvim"

local palette = require("quiet-nvim.palette")

local function hi(name, opts)
	vim.api.nvim_set_hl(0, name, opts)
end

local function apply_links()
	hi("Added", { link = "Normal" })
	hi("Boolean", { link = "Constant" })
	hi("Changed", { link = "Normal" })
	hi("Character", { link = "Constant" })
	hi("Conditional", { link = "Statement" })
	hi("Debug", { link = "Special" })
	hi("Define", { link = "PreProc" })
	hi("Delimiter", { link = "Special" })
	hi("Exception", { link = "Statement" })
	hi("Float", { link = "Constant" })
	hi("Function", { link = "Identifier" })
	hi("Include", { link = "PreProc" })
	hi("Keyword", { link = "Statement" })
	hi("Label", { link = "Statement" })
	hi("Macro", { link = "PreProc" })
	hi("MessageWindow", { link = "Pmenu" })
	hi("Number", { link = "Constant" })
	hi("Operator", { link = "Statement" })
	hi("PopupNotification", { link = "Todo" })
	hi("PreCondit", { link = "PreProc" })
	hi("Removed", { link = "Normal" })
	hi("Repeat", { link = "Statement" })
	hi("SpecialChar", { link = "Special" })
	hi("SpecialComment", { link = "Special" })
	hi("StatusLineTerm", { link = "StatusLine" })
	hi("StatusLineTermNC", { link = "StatusLineNC" })
	hi("StorageClass", { link = "Type" })
	hi("String", { link = "Constant" })
	hi("Structure", { link = "Type" })
	hi("Tag", { link = "Special" })
	hi("Terminal", { link = "Normal" })
	hi("Typedef", { link = "Type" })
	hi("debugBreakpoint", { link = "ModeMsg" })
	hi("debugPC", { link = "CursorLine" })
	hi("lCursor", { link = "Cursor" })
end

local function apply_dark()
	local c = palette.dark
	hi("Normal",        { fg = c.fg, bg = c.bg, ctermfg = 253, ctermbg = 16 })
	hi("ColorColumn",   { bg = c.color_column, ctermbg = 234 })
	hi("Comment",       { fg = c.grey, ctermfg = 242, bold = true, cterm = { bold = true } })
	hi("Conceal",       {})
	hi("Constant",      { fg = c.fg, ctermfg = 253 })
	hi("CurSearch",     { fg = c.cur_search, bg = c.bg, ctermfg = 207, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("Cursor",        { reverse = true, cterm = { reverse = true } })
	hi("CursorColumn",  { bg = c.cursor_line, ctermbg = 236 })
	hi("CursorIM",      { fg = c.bg, bg = c.cursor_im, ctermfg = 16, ctermbg = 154 })
	hi("CursorLine",    { bg = c.cursor_line, ctermbg = 236 })
	hi("CursorLineNr",  { fg = c.fg, bg = c.cursor_line, ctermfg = 253, ctermbg = 236 })
	hi("DiffAdd",       { fg = c.diff_add, bg = c.bg, ctermfg = 34, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("DiffChange",    { fg = c.diff_change, bg = c.bg, ctermfg = 110, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("DiffDelete",    { fg = c.diff_delete, bg = c.bg, ctermfg = 167, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("DiffText",      { fg = c.diff_text, bg = c.bg, ctermfg = 176, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("Directory",     { fg = c.fg, ctermfg = 253 })
	hi("EndOfBuffer",   { fg = c.grey, ctermfg = 242 })
	hi("Error",         { fg = c.err, bg = c.bg, ctermfg = 197, ctermbg = 16, bold = true, reverse = true, cterm = { bold = true, reverse = true } })
	hi("ErrorMsg",      { fg = c.fg, bg = c.bg, ctermfg = 253, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("FoldColumn",    { fg = c.grey, ctermfg = 242 })
	hi("Folded",        { fg = c.grey, bg = c.bg, ctermfg = 242, ctermbg = 16 })
	hi("Identifier",    { fg = c.fg, ctermfg = 253 })
	hi("Ignore",        { fg = c.fg, ctermfg = 253 })
	hi("IncSearch",     { fg = c.inc_search, bg = c.bg, ctermfg = 214, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("LineNr",        { fg = c.line_nr, ctermfg = 240 })
	hi("MatchParen",    { fg = c.match_paren, ctermfg = 199, bold = true, cterm = { bold = true } })
	hi("ModeMsg",       { fg = c.fg, ctermfg = 253, bold = true, cterm = { bold = true } })
	hi("MoreMsg",       { fg = c.fg, ctermfg = 253 })
	hi("NonText",       { fg = c.grey, ctermfg = 242 })
	hi("Pmenu",         { fg = c.bg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248 })
	hi("PmenuExtra",    { fg = c.bg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248 })
	hi("PmenuExtraSel", { fg = c.bg, bg = c.fg, ctermfg = 16, ctermbg = 253 })
	hi("PmenuKind",     { fg = c.bg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248, bold = true, cterm = { bold = true } })
	hi("PmenuKindSel",  { fg = c.bg, bg = c.fg, ctermfg = 16, ctermbg = 253, bold = true, cterm = { bold = true } })
	hi("PmenuMatch",    { fg = c.pmenu_match, bg = c.pmenu_bg, ctermfg = 161, ctermbg = 248 })
	hi("PmenuMatchSel", { fg = c.pmenu_match, bg = c.fg, ctermfg = 161, ctermbg = 253, bold = true, cterm = { bold = true } })
	hi("PmenuSbar",     { fg = c.grey, bg = c.line_nr, ctermfg = 242, ctermbg = 240 })
	hi("PmenuSel",      { fg = c.bg, bg = c.fg, ctermfg = 16, ctermbg = 253 })
	hi("PmenuThumb",    { fg = c.fg, bg = c.fg, ctermfg = 253, ctermbg = 253 })
	hi("PreProc",       { fg = c.fg, ctermfg = 253 })
	hi("Question",      { fg = c.fg, ctermfg = 253 })
	hi("QuickFixLine",  { fg = c.cur_search, bg = c.bg, ctermfg = 207, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("Search",        { fg = c.search, bg = c.bg, ctermfg = 39, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("SignColumn",    { fg = c.fg, ctermfg = 253 })
	hi("Special",       { fg = c.fg, ctermfg = 253 })
	hi("SpecialKey",    { fg = c.grey, ctermfg = 242, bold = true, cterm = { bold = true } })
	hi("SpellBad",      { fg = c.spell_bad, sp = c.spell_bad, ctermfg = 161, undercurl = true, cterm = { underline = true } })
	hi("SpellCap",      { fg = c.spell_cap, sp = c.spell_cap, ctermfg = 32, undercurl = true, cterm = { underline = true } })
	hi("SpellLocal",    { fg = c.spell_local, sp = c.spell_local, ctermfg = 176, undercurl = true, cterm = { underline = true } })
	hi("SpellRare",     { fg = c.spell_rare, sp = c.spell_rare, ctermfg = 37, undercurl = true, cterm = { underline = true } })
	hi("Statement",     { fg = c.fg, ctermfg = 253 })
	hi("StatusLine",    { fg = c.bg, bg = c.fg, ctermfg = 16, ctermbg = 253, bold = true, cterm = { bold = true } })
	hi("StatusLineNC",  { fg = c.grey, bg = c.bg, ctermfg = 242, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("TabLine",       { fg = c.grey, bg = c.bg, ctermfg = 242, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("TabLineFill",   { fg = c.fg, ctermfg = 253 })
	hi("TabLineSel",    { fg = c.bg, bg = c.fg, ctermfg = 16, ctermbg = 253, bold = true, cterm = { bold = true } })
	hi("Title",         {})
	hi("TitleBar",      { fg = c.fg, bg = c.title_bar, ctermfg = 253, ctermbg = 237 })
	hi("TitleBarNC",    { fg = c.grey, bg = c.title_bar_nc, ctermfg = 242, ctermbg = 236 })
	hi("Todo",          { fg = c.todo, ctermfg = 49, bold = true, reverse = true, cterm = { bold = true, reverse = true } })
	hi("ToolbarButton", { fg = c.fg, bg = c.bg, ctermfg = 253, ctermbg = 16, bold = true, cterm = { bold = true } })
	hi("ToolbarLine",   { bg = c.bg, ctermbg = 16 })
	hi("Type",          { fg = c.fg, ctermfg = 253 })
	hi("Underlined",    { fg = c.fg, ctermfg = 253, underline = true, cterm = { underline = true } })
	hi("VertSplit",     { fg = c.grey, bg = c.bg, ctermfg = 242, ctermbg = 16 })
	hi("Visual",        { fg = c.inc_search, bg = c.bg, ctermfg = 214, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("VisualNOS",     { bg = c.cursor_line, ctermbg = 236 })
	hi("WarningMsg",    { fg = c.fg, ctermfg = 253 })
	hi("WildMenu",      { fg = c.search, bg = c.bg, ctermfg = 39, ctermbg = 16, bold = true, cterm = { bold = true } })
end

local function apply_light()
	local c = palette.light
	hi("Normal",        { fg = c.fg, bg = c.bg, ctermfg = 16, ctermbg = 188 })
	hi("ColorColumn",   { bg = c.color_column, ctermbg = 254 })
	hi("Comment",       { fg = c.fg, ctermfg = 16, bold = true, cterm = { bold = true } })
	hi("Conceal",       {})
	hi("Constant",      { fg = c.fg, ctermfg = 16 })
	hi("CurSearch",     { fg = c.cur_search, bg = "#000000", ctermfg = 207, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("Cursor",        { reverse = true, cterm = { reverse = true } })
	hi("CursorColumn",  { bg = c.cursor_line, ctermbg = 255 })
	hi("CursorIM",      { fg = "#000000", bg = c.cursor_im, ctermfg = 16, ctermbg = 154 })
	hi("CursorLine",    { bg = c.cursor_line, ctermbg = 255 })
	hi("CursorLineNr",  { fg = c.fg, bg = c.cursor_line, ctermfg = 16, ctermbg = 255 })
	hi("DiffAdd",       { fg = c.diff_add, bg = "#000000", ctermfg = 114, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("DiffChange",    { fg = c.diff_change, bg = "#000000", ctermfg = 146, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("DiffDelete",    { fg = c.diff_delete, bg = "#000000", ctermfg = 174, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("DiffText",      { fg = c.diff_text, bg = "#000000", ctermfg = 176, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("Directory",     { fg = c.fg, ctermfg = 16 })
	hi("EndOfBuffer",   { fg = c.grey, ctermfg = 241 })
	hi("Error",         { fg = c.err, bg = "#000000", ctermfg = 197, ctermbg = 16, bold = true, reverse = true, cterm = { bold = true, reverse = true } })
	hi("ErrorMsg",      { fg = c.fg, bg = c.bg, ctermfg = 16, ctermbg = 188, reverse = true, cterm = { reverse = true } })
	hi("FoldColumn",    { fg = c.grey, ctermfg = 241 })
	hi("Folded",        { fg = c.grey, bg = c.bg, ctermfg = 241, ctermbg = 188 })
	hi("Identifier",    { fg = c.fg, ctermfg = 16 })
	hi("Ignore",        { fg = c.fg, ctermfg = 16 })
	hi("IncSearch",     { fg = c.inc_search, bg = "#000000", ctermfg = 214, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("LineNr",        { fg = c.line_nr, ctermfg = 248 })
	hi("MatchParen",    { fg = c.match_paren, bg = c.bg, ctermfg = 199, ctermbg = 188, bold = true, cterm = { bold = true } })
	hi("ModeMsg",       { fg = c.fg, ctermfg = 16, bold = true, cterm = { bold = true } })
	hi("MoreMsg",       { fg = c.fg, ctermfg = 16 })
	hi("NonText",       { fg = c.grey, ctermfg = 241 })
	hi("Pmenu",         { fg = c.fg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248 })
	hi("PmenuExtra",    { fg = c.fg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248 })
	hi("PmenuExtraSel", { fg = c.bg, bg = c.fg, ctermfg = 188, ctermbg = 16 })
	hi("PmenuKind",     { fg = c.fg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248, bold = true, cterm = { bold = true } })
	hi("PmenuKindSel",  { fg = c.bg, bg = c.fg, ctermfg = 188, ctermbg = 16, bold = true, cterm = { bold = true } })
	hi("PmenuMatch",    { fg = c.pmenu_match, bg = c.pmenu_bg, ctermfg = 160, ctermbg = 248 })
	hi("PmenuMatchSel", { fg = c.pmenu_match, bg = c.fg, ctermfg = 160, ctermbg = 16, bold = true, cterm = { bold = true } })
	hi("PmenuSbar",     { fg = c.fg, bg = c.color_column, ctermfg = 16, ctermbg = 254 })
	hi("PmenuSel",      { fg = c.bg, bg = c.fg, ctermfg = 188, ctermbg = 16 })
	hi("PmenuThumb",    { fg = c.fg, bg = c.fg, ctermfg = 16, ctermbg = 16 })
	hi("PreProc",       { fg = c.fg, ctermfg = 16 })
	hi("Question",      { fg = c.fg, ctermfg = 16 })
	hi("QuickFixLine",  { fg = c.cur_search, bg = "#000000", ctermfg = 207, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("Search",        { fg = c.search, bg = "#000000", ctermfg = 39, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("SignColumn",    { fg = c.fg, ctermfg = 16 })
	hi("Special",       { fg = c.fg, ctermfg = 16 })
	hi("SpecialKey",    { fg = c.grey, ctermfg = 241, bold = true, cterm = { bold = true } })
	hi("SpellBad",      { fg = c.spell_bad, bg = c.bg, sp = c.spell_bad, ctermfg = 124, ctermbg = 188, undercurl = true, cterm = { underline = true } })
	hi("SpellCap",      { fg = c.spell_cap, bg = c.bg, sp = c.spell_cap, ctermfg = 25, ctermbg = 188, undercurl = true, cterm = { underline = true } })
	hi("SpellLocal",    { fg = c.spell_local, bg = c.bg, sp = c.spell_local, ctermfg = 90, ctermbg = 188, undercurl = true, cterm = { underline = true } })
	hi("SpellRare",     { fg = c.spell_rare, bg = c.bg, sp = c.spell_rare, ctermfg = 30, ctermbg = 188, undercurl = true, cterm = { underline = true } })
	hi("Statement",     { fg = c.fg, ctermfg = 16 })
	hi("StatusLine",    { fg = c.status_line_fg, bg = "#000000", ctermfg = 255, ctermbg = 16, bold = true, cterm = { bold = true } })
	hi("StatusLineNC",  { fg = c.fg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248 })
	hi("TabLine",       { fg = c.fg, bg = c.pmenu_bg, ctermfg = 16, ctermbg = 248 })
	hi("TabLineFill",   { fg = c.fg, bg = c.bg, ctermfg = 16, ctermbg = 188 })
	hi("TabLineSel",    { fg = c.status_line_fg, bg = "#000000", ctermfg = 255, ctermbg = 16, bold = true, cterm = { bold = true } })
	hi("Title",         {})
	hi("TitleBar",      { fg = c.fg, bg = c.title_bar, ctermfg = 16, ctermbg = 255 })
	hi("TitleBarNC",    { fg = c.grey, bg = c.title_bar_nc, ctermfg = 241, ctermbg = 255 })
	hi("Todo",          { fg = c.todo, bg = "#000000", ctermfg = 49, ctermbg = 16, bold = true, reverse = true, cterm = { bold = true, reverse = true } })
	hi("ToolbarButton", { fg = c.fg, bg = c.bg, ctermfg = 16, ctermbg = 188, bold = true, cterm = { bold = true } })
	hi("ToolbarLine",   { bg = c.bg, ctermbg = 188 })
	hi("Type",          { fg = c.fg, ctermfg = 16 })
	hi("Underlined",    { fg = c.fg, ctermfg = 16, underline = true, cterm = { underline = true } })
	hi("VertSplit",     { fg = c.grey, bg = c.bg, ctermfg = 241, ctermbg = 188 })
	hi("Visual",        { fg = c.inc_search, bg = "#000000", ctermfg = 214, ctermbg = 16, reverse = true, cterm = { reverse = true } })
	hi("VisualNOS",     { bg = c.cursor_line, ctermbg = 255 })
	hi("WarningMsg",    { fg = c.fg, ctermfg = 16 })
	hi("WildMenu",      { fg = c.fg, bg = c.cursor_line, ctermfg = 16, ctermbg = 255, bold = true, cterm = { bold = true } })
end

apply_links()

local mode = vim.o.background == "light" and palette.light or palette.dark
if vim.o.background == "light" then
	apply_light()
else
	apply_dark()
end

for i, hex in ipairs(mode.terminal) do
	vim.g["terminal_color_" .. (i - 1)] = hex
end
